apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsperf
  labels:
    app: dnsperf
spec:
  replicas: 8
  selector:
    matchLabels:
      app: dnsperf
  template:
    metadata:
      labels:
        app: dnsperf
    spec:
      containers:
      - name: dnsperf
        image: biennt/dnsperf
        imagePullPolicy: IfNotPresent
        env:
        - name: datafile
          value: "example10m.txt"
        - name: server
          value: "192.168.100.11"
        - name: thread
          value: "4"
      restartPolicy: Always

